#!/bin/bash
# Activate Conda environment
source /home/juliayoo/miniconda/etc/profile.d/conda.sh
conda activate <model>

# Run your actual command
/path/to/your/python_script.py

[Unit]
Description=mything: do my own thing
After=multi-user.target

[Service]
ExecStart=/usr/local/bin/ard_5.py
Restart=always
StartLimitInterval=10
RestartSec=10

[Install]
WantedBy=multi-user.target